export enum CollectionNames {
  countersLocationInvoicesDone = 'countersLocationInvoicesDone',
  countersOrganizationInvoicesDone = 'countersOrganizationInvoicesDone',
  countersLocationOrderNumber = 'countersLocationOrderNumber',
  files = 'files',
  invoiceAdjustmentTypes = 'invoiceAdjustmentTypes',
  invoiceAdjustments = 'invoiceAdjustments',
  invoiceProducts = 'invoiceProducts',
  invoices = 'invoices',
  locations = 'locations',
  notificationsQueue = 'notificationsQueue',
  orderProducts = 'orderProducts',
  orders = 'orders',
  organizations = 'organizations',
  permissions = 'permissions',
  productCategories = 'productCategories',
  productPriceChanges = 'productPriceChanges',
  products = 'products',
  suppliers = 'suppliers',
  unitTypes = 'unitTypes',
  users = 'users',
  usersConfigs = 'usersConfigs',
}
